### PR TITLE
Fix editorconfig

### PR DESCRIPTION
**Pull request by szepeviktor**
- add [missing keys](https://EditorConfig.org)
- make GitHub display 4-space wide TAB characters

### CODE REVIEW

**Comment by crstauf** [comment]
The config is not broken, and the decisions there are intentional (I prefer four-spaced tabs, but others do not), but I should probably add `root: true`. 👍

**Comment by szepeviktor** [comment]
> (I prefer four-spaced tabs, but others do not)

There is a misunderstanding. A TAB character is always 1 character.
I just can't review code when GitHub displays 8-wide TABs.

**Comment by crstauf** [comment]
> GitHub displays 8-wide TABs

That's peculiar: the PRs for QMX display with 4-wide tabs for me.

**Comment by szepeviktor** [comment]
You may have a non-default setting.

image

https://github.com/settings/appearance

**Comment by crstauf** [comment]
Ahh, you are correct. Why not set that for yourself?

**Comment by szepeviktor** [comment]
> Why not set that for yourself?

I want to send PR-s with `indent_size = 4`

**Comment by crstauf** [comment]
> I want to send PR-s with `indent_size = 4`

What about someone that "can't review code with [4-wide] tabs"? :wink:

**Pull request closed without merging**
