### PR TITLE
Make classes clean

### PR DESCRIPTION
**Pull request by szepeviktor**
Restructure classes to remove side-effects.
Only a single `add_action( 'plugins_loaded'` remains.
```
src/
├── Collector
│   ├── ACF.php
│   ├── Constants.php
│   ├── Files.php
│   ├── Heartbeat.php
│   ├── ImageSizes.php
│   ├── Paths.php
│   └── Time.php
├── Data
│   ├── ACF.php
│   ├── Constants.php
│   ├── Files.php
│   ├── ImageSizes.php
│   ├── Paths.php
│   └── Time.php
├── Output
│   └── Html
│       ├── ACF.php
│       ├── Constants.php
│       ├── Files.php
│       ├── Heartbeat.php
│       ├── ImageSizes.php
│       ├── Paths.php
│       └── Time.php
└── Plugin.php
```

image

It is half-done! 🧊 

@crstauf What do you think?

### CODE REVIEW

**Comment by crstauf** [comment]
The structure is intentional, so a developer can easily install only certain panels.

At this time I see the current structure as more valuable than the proposed structure. If value can be proved for the proposed structure I will consider it.

**Comment by szepeviktor** [comment]
All right.
The only thing I can say is that I write code that looks like a web application.

**Comment by crstauf** [comment]
QMX has this structure for a long time, until I realized from time-to-time I only wanted a few extra panels, not all of them.

**Comment by szepeviktor** [comment]
```php
$enabled_panels = apply_filters('my_lovely_qmx_filter`, ['acf', 'constants', 'files' ... ]);
```

**Comment by szepeviktor** [comment]
Let's see https://github.com/johnbillion/query-monitor/issues/819

**Comment by crstauf** [comment]
Yep, that's an unnecessary step if the files don't exist in the first place. I will probably introduce a filter like this soon, but definitely keeping the existing structure for now.

**Comment by crstauf** [comment]
> The only thing I can say is that I write code that looks like a web application.

Congrats on satisfying your own standards. I'm doing the same thing. 👼

**Pull request closed without merging**
