### PR TITLE
Automate plugin version detection

### PR DESCRIPTION
**Pull request by szepeviktor**
1. From now on you don't have to edit on 3 places
2. This is my favorite plugin so I contribute every day 🎁

### CODE REVIEW

**Comment by crstauf** [comment]
Interesting. Can the constant be defined with the version from the plugin header?

```php
define( 'QMX_TESTED_WITH_QM', get_plugin_data( __FILE__ )['QM tested up to'] ?? '3.0.0' );
```

**Comment by szepeviktor** [comment]
I thought I could persuade you to leave constants behind ...

**Comment by crstauf** [comment]
> I thought I could persuade you to leave constants behind ...

@szepeviktor What's the benefit?

**Comment by szepeviktor** [comment]
Anything global (variable, constant, function, class without namespace) is more like a script, not an application.
PHP started as a template engine, then it was a scripting language, from 7.0 on it is like a programing language.

**Comment by crstauf** [comment]
@szepeviktor So there's not a real benefit, it's more a perspective of coding?

**Comment by szepeviktor** [comment]
Anyone with engineering qualities has a natural aversion to scripts.

**Comment by szepeviktor** [comment]
BTW Anything global is hard to unittest, hard to statically analyze, hard to find bugs.

**Review by crstauf — APPROVED** [review]

**Pull request merged**
