### PR TITLE
ACF Collector

### LINKED ISSUE #10: ACF Collector

### PR DESCRIPTION
**Pull request by crstauf**
Closes #10.

### CODE REVIEW

**Comment by crstauf** [comment]
@wpsumo You may be interested in this. Note that it's currently a draft, so is incomplete.

**Comment by crstauf** [comment]
@wpsumo I think I'm ready to merge this; have you reviewed, and have any suggestions or requests?

**Comment by wpsumo** [comment]
@crstauf Looks good to me would have to test it on staging to see how the new changes works in the reality. Pushed to the wp repo today or?

**Comment by crstauf** [comment]
@wpsumo There is no WordPress repository for QMX, just the download from the GitHub repository.

**Comment by wpsumo** [comment]
@crstauf Just remembered once I saw your reply! Ok time to test it then!

**Comment by crstauf** [comment]
@wpsumo Any feedback before I merge?

**Comment by wpsumo** [comment]
@crstauf Will it show acf fields both in wp-admin and frontend with the fix? My concerns has been to find the more specific report of the performance and queries both frontend and backend.

**Comment by crstauf** [comment]
@wpsumo Yes, it collects ACF fields on both frontend and backend.

**Comment by wpsumo** [comment]
Will check it out on staging.

**Pull request merged**
