### PR TITLE
PHPDoc tag-based collector registration

### PR DESCRIPTION
**Pull request by szepeviktor**
@crstauf How about registering collectors based on PHPDoc tags?

_This is not PR._

### CODE REVIEW

**Comment by crstauf** [comment]
What is the advantage this approach has over a filter?

**Comment by szepeviktor** [comment]
There will be no difference. The PHPDoc tag will add a filter too.

The advantage is: we will have clean class files: no [side-effect](https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-1-basic-coding-standard.md#23-side-effects) in class files.

**Comment by szepeviktor** [comment]
... providing you want to write application code, not a script.

**Comment by crstauf** [comment]
Thanks for the explanation. For now, I'll keep things as-is, to match with WordPress' approach and make the onboarding for junior devs easier/quicker.

**Comment by szepeviktor** [comment]
All right.
https://github.com/johnbillion/query-monitor/pull/877

**Pull request closed without merging**
