### PR TITLE
Error Shown incase Query Monitor is not active.

### PR DESCRIPTION
**Pull request by varunsridharan**
Error Shown incase Query Monitor is not active.

image

### CODE REVIEW

**Comment by crstauf** [comment]
@varunsridharan This will likely need some fixing, but please try loading as a regular plugin, and see if the issue exists then.

**Comment by varunsridharan** [comment]
@crstauf  well as i said in case if i deactivate Query Monitor plugin then it throws this error. so adding a check before loading the plugin will solve this. :-)

**Comment by crstauf** [comment]
@varunsridharan It already does.

Did you test as a normal plugin instead of an MU-plugin?

**Comment by crstauf** [comment]
Mmm, I see the issue now. Will get it fixed. Thanks.

**Comment by crstauf** [comment]
@varunsridharan Fixed.

**Pull request closed without merging**
